spring:
  application:
    name: Spring mybatsic 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gas?useSSL=false&verifyServerCertificate=false&serverTimezone=Asia/Shanghai
    name: MySQL Connection
    username: root
    password: password
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
